# Generated by Django 2.2.5 on 2024-03-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240305_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='banner', verbose_name='广告图片'),
        ),
    ]
