# Generated by Django 2.2.5 on 2024-03-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240305_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='orders',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
    ]
